name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Run Eslint
        run: yarn lint

      - name: Run Prettier
        run: yarn format

      - name: Run tests
        run: yarn test:gas

      - name: Codechecks
        env:
          CC_SECRET: ${{ secrets.CC_SECRET }}
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
        run: npx codechecks
